In [1]:
import pickle
import numpy
import pandas

In [19]:
with open('../results/x_track.pickle', 'rb') as f:
    x_track = pickle.load(f)
x_track

[tensor([[0.7943],
         [7.9371],
         [6.8932],
         ...,
         [3.4952],
         [4.0828],
         [5.3534]], device='cuda:0', requires_grad=True),
 tensor([[ 6.4747],
         [-2.6827],
         [-2.5961],
         ...,
         [ 9.9058],
         [ 7.0109],
         [ 3.9265]], device='cuda:0', requires_grad=True),
 tensor([[6.7449],
         [8.1616],
         [3.4848],
         ...,
         [3.3498],
         [8.4204],
         [7.6085]], device='cuda:0', requires_grad=True),
 tensor([[-1.4941],
         [ 6.5703],
         [ 7.2222],
         ...,
         [ 6.4423],
         [ 5.5065],
         [ 1.3748]], device='cuda:0', requires_grad=True),
 tensor([[7.7222],
         [0.8097],
         [1.1450],
         ...,
         [3.8495],
         [5.8011],
         [3.2858]], device='cuda:0', requires_grad=True),
 tensor([[ 0.6500],
         [-0.4018],
         [ 1.4652],
         ...,
         [-0.9337],
         [ 2.0033],
         [ 3.5048]], device='cuda:0', r