In [36]:
import pickle
import pandas as pd
import numpy as np
import time

In [46]:
from sklearn.decomposition import SparsePCA
from sklearn.decomposition import MiniBatchSparsePCA
from sklearn.decomposition import TruncatedSVD

In [38]:
with open('../results/x.pickle', mode='rb') as f:
    x = pickle.load(f)

In [39]:
x

array([[1., 1., 1., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [1., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.]], shape=(943, 1650))

In [45]:
start = time.time()

transformer = SparsePCA(n_components=16, random_state=42)

X = x@x.T
transformer.fit(X)
X_trsf = transformer.transform(X)
print(X_trsf)
print(X_trsf.shape)

end = time.time()
print('time :', end-start)

[[ 25.89913891 -14.62534205  51.91227953 ...  27.06423124  33.467753
    8.65557573]
 [-63.96125865  -5.21681544  -7.70857005 ... -40.58383198 -14.30328372
  -18.6500506 ]
 [-68.7345558  -48.81838808 -36.92247844 ... -24.07812614  -3.93269504
  -25.28152398]
 ...
 [-74.23127841  -2.27355621 -34.35959524 ... -19.36828789   8.57081721
  -22.75363056]
 [-44.33242986  -8.10205677 -19.21148007 ...  12.38932991 -16.23195989
  -10.98784345]
 [209.25722735  35.442505   -27.2735415  ...  11.63796097  52.21164228
   48.31144683]]
(943, 16)
time : 567.2709226608276


In [47]:
svd = TruncatedSVD(n_components=16, random_state=42)
u = svd.fit_transform(x)
v = svd.components_
print(u, v)

[[ 4.85645296e+00 -3.99194280e-01  5.75403863e-01 ... -1.47317697e-01
   1.11745025e-01 -5.20785008e-01]
 [ 1.57533151e+00  2.47939177e+00  1.46275221e+00 ...  6.14819719e-01
   1.83610319e-01  1.24244791e-01]
 [ 3.77319306e-01  6.58728226e-01  4.31538807e-01 ... -1.98482621e-01
   1.41989430e-01 -4.86131557e-02]
 ...
 [ 1.07614935e+00  1.50573453e+00  1.47039807e-03 ...  5.70598090e-02
   5.93631418e-01  1.72155419e-01]
 [ 3.43227000e+00 -1.44210450e-02  1.14737408e+00 ...  3.28466831e-01
  -1.62569245e-01  3.13109887e-01]
 [ 6.04040896e+00 -1.13785892e-01 -2.78721692e+00 ... -1.13780592e-01
   6.15400552e-01  6.12704192e-01]] [[ 0.09972284  0.03814507  0.01940138 ...  0.          0.00065585
   0.00072281]
 [ 0.10242211 -0.01153166  0.02416116 ...  0.         -0.00061008
  -0.00087239]
 [-0.04504041 -0.06267296 -0.01336823 ... -0.         -0.00031226
  -0.00027046]
 ...
 [-0.04118159  0.01367536 -0.00411273 ...  0.          0.00423097
  -0.00119634]
 [-0.03205811  0.01465168  0.024542

In [49]:
start = time.time()

transformer = MiniBatchSparsePCA(n_components=16, batch_size=20,
                                 random_state=42)

transformer.fit(x@x.T)
x_trsf_batch = transformer.transform(x@X.T)
print(x_trsf_batch)
print(x_trsf_batch.shape)

end = time.time()
print('time :', end-start)

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 943 is different from 1650)

In [ ]:
transformer = SparsePCA()

array([[1., 1., 1., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [1., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.]], shape=(943, 1650))

In [23]:
temp = np.array([[1, 1, 1],
                 [1, 0, 0],
                 [0, 0, 0]])
temp

array([[1, 1, 1],
       [1, 0, 0],
       [0, 0, 0]])

In [24]:
temp@temp.T

array([[3, 1, 0],
       [1, 1, 0],
       [0, 0, 0]])

In [19]:
print('x@x.T')
print(x@x.T)
print('x.T@x')
print(x.T@x)

x@x.T
[[108.   5.   2. ...   7.  11.  27.]
 [  5.  37.   0. ...   4.   6.   6.]
 [  2.   0.  16. ...   1.   3.   1.]
 ...
 [  7.   4.   1. ...  20.   4.   5.]
 [ 11.   6.   3. ...   4.  78.  17.]
 [ 27.   6.   1. ...   5.  17. 124.]]
x.T@x
[[353.  56.  35. ...   0.   1.   1.]
 [ 56.  84.  13. ...   0.   1.   1.]
 [ 35.  13.  47. ...   0.   0.   1.]
 ...
 [  0.   0.   0. ...   0.   0.   0.]
 [  1.   1.   0. ...   0.   1.   0.]
 [  1.   1.   1. ...   0.   0.   1.]]
